export const speakers = [
	{
		name: "Milos Manic",
		slug: "milos-manic",
		imageSmall: { url: "/assets/speakers/milos.jpeg" },
		title: "IEEE IES President | Director, VCU Cybersecurity Center Virginia Commonwealth University",
		enabled: true,
	},
	{
		name: "Yajun Pan",
		slug: "yajun-pan",
		imageSmall: { url: "/assets/speakers/ya jun.jpeg" },
		title: "IEEE IES VP of Membership | Professor at Dalhousie University",
		enabled: true,
	},
	{
		name: "Tripura Pidikiti",
		slug: "tripura-pidikiti",
		imageSmall: { url: "/assets/speakers/tripura.jpeg" },
		title: "IEEE IES SAC Member | IEEE Hyderabad Section Chair | Professor at RVR and JC College of Engineering",
		enabled: true,
	},
	{
		name: "Chaturika Wickramasinghe",
		slug: "chaturika-wickramasinghe",
		imageSmall: { url: "/assets/speakers/Chaturika Wickramasinghe.jpeg" },
		title: "IEEE IES YP Committee Chair | Data Scientist",
		enabled: true,
	},
	{
		name: "Hani Vahedi",
		slug: "hani-vahedi",
		imageSmall: { url: "/assets/speakers/Hani Vahedi.jpeg" },
		title: "Chapter&Joint Chapter Coordinator | Professor at Delft University of technologies",
		enabled: true,
	},
	{
		name: "Ala Chalghaf",
		slug: "ala-chalghaf",
		imageSmall: { url: "/assets/speakers/Ala_Chalghaf.jpg" },
		title: "IES Student Activities Committee Chair | Lead Data Scientist at DeepVolt | Technical Consultant at Oratio Technologies",
		enabled: true,
	},
	{
		name: "Aziz Ben Kbaier",
		slug: "aziz-ben-kbaier",
		imageSmall: { url: "/assets/speakers/Aziz_Ben_Kbaier.jpg" },
		title: "IES Student Activities Committee Member | Software Engineer",
		enabled: true,
	},
];
