export const team = [
  {
    name: "Ala Chalghaf",
    title: "General Chair",
    slug: "rauchg",
    image: { url: "/assets/Team/Ala_Chalghaf.jpg" },
  },
  {
    name: "Aziz Ben Kbaier",
    title: "General Chair",
    slug: "rauchg",
    image: { url: "/assets/Team/Aziz_Ben_Kbaier.jpg" },
  },
  {
    name: "Malek Miri",
    title: "Program Chair",
    slug: "rauchg",
    image: { url: "/assets/Team/Malek_Miri.jpg" },
  },
  {
    name: "Mohamed Rebai",
    title: "Technical Track Chair",
    slug: "rauchg",
    image: { url: "/assets/Team/Mohamed_REBAI.png" },
  },
  {
    name: "Aziz Chalghaf",
    title: "Social Activities Chair",
    slug: "rauchg",
    image: { url: "/assets/Team/Aziz_Chalghaf.jpg" },
  },
  {
    name: "Khalil Masmoudi",
    title: "Venue Coordinator",
    slug: "rauchg",
    image: { url: "/assets/Team/Khalil_Masmoudi.jpg" },
  },
  {
    name: "Mayssa Larguech",
    title: "Participants Coordinator",
    slug: "rauchg",
    image: { url: "/assets/Team/Mayssa_Larguech.png" },
  },
  {
    name: "Tawfik Sallemi",
    title: "Treasurer and Logistics Team Member",
    slug: "rauchg",
    image: { url: "/assets/Team/Tawfik_Sallemi.png" },
  },
  {
    name: "Takwa Fguiri",
    title: "Sponsorship Chair",
    slug: "rauchg",
    image: { url: "/assets/Team/Takwa_Fguiri.jpg" },
  },
  {
    name: "Chayma Bouattour",
    title: "Sponsorship Team Member",
    slug: "rauchg",
    image: { url: "/assets/Team/Chayma_Bouattour.jpg" },
  },
  {
    name: "Adam Klibi",
    title: "Sponsorship Team Member",
    slug: "rauchg",
    image: { url: "/assets/Team/Adam_Klibi.jpg" },
  },
  {
    name: "Eya Ayadi",
    title: "Sponsorship Team Member",
    slug: "rauchg",
    image: { url: "/assets/Team/Eya_Ayadi.png" },
  },
  {
    name: "Maram Bouaziz",
    title: "Sponsorship Team Member",
    slug: "rauchg",
    image: { url: "/assets/Team/Maram_Bouaziz.jpg" },
  },
  {
    name: "Asma Basly",
    title: "IEEE Funding Co-Chair",
    slug: "rauchg",
    image: { url: "/assets/Team/Asma_Basly.jpeg" },
  },
  {
    name: "Khaldoun Taktak",
    title: "IEEE Funding Co-Chair",
    slug: "rauchg",
    image: { url: "/assets/Team/Khaldoun_Taktak.jpg" },
  },
  {
    name: "Achref Mejri",
    title: "Logistics Chair",
    slug: "rauchg",
    image: { url: "/assets/Team/Achraf_mejri.jpg" },
  },
  {
    name: "Yesmine Mejri",
    title: "Logistics Team Member",
    slug: "rauchg",
    image: { url: "/assets/Team/Yesmine_Mejri.jpg" },
  },
  {
    name: "Jaber soyed",
    title: "Logistics Team Member",
    slug: "rauchg",
    image: { url: "/assets/Team/oc_boy.png" },
  },
  {
    name: "Mohamed Bouzayani",
    title: "Logistics Team Member",
    slug: "rauchg",
    image: { url: "/assets/Team/Mohamed_Bouzayani.jpg" },
  },
  {
    name: "Mohamed Aziz Hbaili",
    title: "Media and Communication Chair",
    slug: "rauchg",
    image: { url: "/assets/Team/Mohamed_Aziz_Hbaili.jpg" },
  },
  {
    name: "Farah Lakhal",
    title: "Media and Communication Team Member",
    slug: "rauchg",
    image: { url: "/assets/Team/Farah_Lakhal.jpg" },
  },
  {
    name: "rayen hamdi",
    title: "Media and Communication Team Member",
    slug: "rauchg",
    image: { url: "/assets/Team/rayen_hamdi.jpg" },
  },
  {
    name: "Elyess Ben Sassi",
    title: "Media and Communication Team Member",
    slug: "rauchg",
    image: { url: "/assets/Team/oc_boy.png" },
  },
  {
    name: "Amina Bayoudh",
    title: "Media and Communication Team Member",
    slug: "rauchg",
    image: { url: "/assets/Team/Amina_Bayoudh.png" },
  },
  {
    name: "Eya Jaoua",
    title: "Media and Communication Team Member",
    slug: "rauchg",
    image: { url: "/assets/Team/Eya_jaoua.jpg" },
  },
  {
    name: "Islem Mzoughi",
    title: "Media and Communication Team Member",
    slug: "rauchg",
    image: { url: "/assets/Team/Islem_Mzoughi.png" },
  },
  {
    name: "Mohamed Fares Frini",
    title: "Webmaster",
    slug: "rauchg",
    image: { url: "/assets/Team/Mohamed_Fares_Frini.jpg" },
  },
  {
    name: "Bassem Gouty",
    title: "Webmaster",
    slug: "rauchg",
    image: { url: "/assets/Team/Bassem_Gouty.jpg" },
  },
  {
    name: "Oumayma Masmoudi",
    title: "Secretary General",
    slug: "rauchg",
    image: { url: "/assets/Team/oumayma_masmoudi.png" },
  },
];
